name: Clone and Copy Workflow

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main  # Adjust this to match your default branch

jobs:
  clone-and-copy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone repo1
      - name: Clone repo1
        uses: actions/checkout@v2
        with:
          repository: IndranilJ/repo1
          path: folderA
          token: ${{ secrets.GH_TOKEN }}

      # Step 2: Clone repo2
      - name: Clone repo2
        # run: |
        #   git clone https://github.com/IndranilJ/repo2.git folderB
        # working-directory: ${{ github.workspace }}
        uses: actions/checkout@v2
        with:
          repository: IndranilJ/repo2
          path: folderB
          token: ${{ secrets.GH_TOKEN }}

      # Step 3: Copy a File from FolderA to FolderB
      - name: Modify and Copy File
        run: |
          ls -lrt folderA
          date >> folderA/file1.txt
          echo modified in repo2 workflow folderA/file1.txt
          yes | cp -rf folderA/file1.txt folderB/
          ls -lrt folderB
          date >> folderB/file2.txt
          echo modified in repo2 workflow folderB/file2.txt
        working-directory: ${{ github.workspace }}

      # Step 4: Commit and Push Changes to RepoB
      - name: Commit and Push
        run: |
          cd folderB
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@example.com"
          git add .
          git commit -m "Copy file from FolderA"
          git push origin main
        working-directory: ${{ github.workspace }}
